language: cpp
os:
  - linux
compiler:
  - gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 'ci/before_install_linux.sh' ; fi
install: 
  - mkdir build
  - cd build 
  - cmake ..
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then '../ci/script_linux.sh' ; fi
after_failure:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then '../ci/after_failure_linux.sh' ; fi
